### PR TITLE
Changed to https and changed packages.json creation

### PR DESCRIPTION
**Pull request by LarsCJensen**
I have tested lip.install("Credit Info") with great success.

### CODE REVIEW

**Comment by justFredster** [comment]
When I try this `lip.Install("creditinfo")`

I get this in the immediate window:
Checking version for LIP
Package/Add-on 'lip' not found in local stores!
Package 'lip' not found!
Package/Add-on 'creditinfo' not found in local stores!
Package 'creditinfo' not found!

1. Why can't it find LIP?
2. Do we really want to force the consultants to use the Display name? Would be better with uniqueName.
3. For next release, we should remove the local stores thing. Maybe a new implementation will be made in the future, but right now it is just a bit in the way.
4. Suggestion: If the package sought after has the name "lip" it should not look in local stores.

**Comment by LarsCJensen** [comment]
That's strange. I tried that and it worked. It worked when I tried it now;

lip.install("Credit Info"). Are you sure the changes in lip are in the thing you try? That is:

Private Const BaseURL As String = "https://api.lime-bootstrap.com"
Private Const PackageStoreApiURL As String = "/addons/"
Private Const AppStoreApiURL As String = "/addons/"

**Comment by justFredster** [comment]
@LarsCJensen Tested it again but it still doesn't work. Here is the output printed in the Immediate Window:

lip.Install "Credit Info"
Checking version for LIP
Package/Add-on 'lip' not found in local stores!
Package 'lip' not found!
Package/Add-on 'Credit Info' not found in local stores!
Package 'Credit Info' not found!

**Comment by justFredster** [comment]
I will continue to debug this next week.

**Comment by justFredster** [comment]
Installing using LIP.Install("Credit Info") now works!

**Pull request merged**
